name: Build & Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to release (e.g. v0.0.1)'
        required: true

jobs:
  build-and-release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Camel case
        uses: ./.github/actions/build
        with:
          extension-name: camelcase

      - name: Build Kebab case
        uses: ./.github/actions/build
        with:
          extension-name: kebabcase

      - name: Build Snake case
        uses: ./.github/actions/build
        with:
          extension-name: snakecase

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.inputs.version }}
          tag_name: ${{ github.event.inputs.version }}
          files: |
            camelcase.popclipext.tar.gz
            kebabcase.popclipext.tar.gz
            snakecase.popclipext.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
