name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          cp -r camelcase camelcase.popclipext
          cp -r kebabcase kebabcase.popclipext
          cp -r snakecase snakecase.popclipext

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            camelcase.popclipext
            kebabcase.popclipext
            snakecase.popclipext
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
