name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/build
        with:
          extension-name: camelcase

      - uses: ./.github/actions/build
        with:
          extension-name: kebabcase

      - uses: ./.github/actions/build
        with:
          extension-name: snakecase

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            camelcase.popclipext.tar.gz
            kebabcase.popclipext.tar.gz
            snakecase.popclipext.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
